### ISSUE TITLE
Error - No lexer found when building repository

### ISSUE THREAD

**Issue by justjoehere** [enkessler/cql#9]
Attempting to build repository and receiving an error

```
require 'cql'
require 'csv'
@myrepo=CQL::Repository.new 'C:/project/features'
```

Tried in Ruby 218 and 223.

From Gemlock file
```
    cql (1.1.0)
      cuke_modeler
    cucumber (1.3.20)
      builder (>= 2.1.2)
      diff-lcs (>= 1.1.3)
      gherkin (~> 2.12)
      multi_json (>= 1.7.5, < 2.0)
      multi_test (>= 0.1.2)
    cuke_modeler (0.4.0)
      gherkin (< 5.0)
      json (~> 1.0)
      multi_json (~> 1.0)
```
Error trace

```
C:/railsinstaller/ruby/2.1.0/i386-mingw32. Reverting to Ruby lexer.
C:/railsinstaller/ruby/gems/2.1.0/gems/gherkin-2.12.2-x86-mingw32/lib/gherkin/i18n.rb:108:in `rescue in lexer': No lexer was found for en (cannot load such file -- gherkin/lexer/en). Supported languages are listed in gherkin/i18n.json. (Gherkin::I18n::LexerNotFound)
	from C:/railsinstaller/ruby/gems/2.1.0/gems/gherkin-2.12.2-x86-mingw32/lib/gherkin/i18n.rb:97:in `lexer'
	from C:/railsinstaller/ruby/gems/2.1.0/gems/gherkin-2.12.2-x86-mingw32/lib/gherkin/parser/parser.rb:139:in `transition_table'
	from C:/railsinstaller/ruby/gems/2.1.0/gems/gherkin-2.12.2-x86-mingw32/lib/gherkin/parser/parser.rb:128:in `build_transition_map'
	from C:/railsinstaller/ruby/gems/2.1.0/gems/gherkin-2.12.2-x86-mingw32/lib/gherkin/parser/parser.rb:124:in `transition_map'
	from C:/railsinstaller/ruby/gems/2.1.0/gems/gherkin-2.12.2-x86-mingw32/lib/gherkin/parser/parser.rb:91:in `initialize'
	from C:/railsinstaller/ruby/gems/2.1.0/gems/gherkin-2.12.2-x86-mingw32/lib/gherkin/parser/parser.rb:68:in `new'
	from C:/railsinstaller/ruby/gems/2.1.0/gems/gherkin-2.12.2-x86-mingw32/lib/gherkin/parser/parser.rb:68:in `push_machine'
	from C:/railsinstaller/ruby/gems/2.1.0/gems/gherkin-2.12.2-x86-mingw32/lib/gherkin/parser/parser.rb:31:in `parse'
	from C:/railsinstaller/ruby/gems/2.1.0/gems/cuke_modeler-0.4.0/lib/cuke_modeler/parsing.rb:94:in `parse_text'
	from C:/railsinstaller/ruby/gems/2.1.0/gems/cuke_modeler-0.4.0/lib/cuke_modeler/feature_file.rb:67:in `parse_file'
	from C:/railsinstaller/ruby/gems/2.1.0/gems/cuke_modeler-0.4.0/lib/cuke_modeler/feature_file.rb:24:in `initialize'
	from C:/railsinstaller/ruby/gems/2.1.0/gems/cuke_modeler-0.4.0/lib/cuke_modeler/containing.rb:11:in `new'
	from C:/railsinstaller/ruby/gems/2.1.0/gems/cuke_modeler-0.4.0/lib/cuke_modeler/containing.rb:11:in `build_child_element'
	from C:/railsinstaller/ruby/gems/2.1.0/gems/cuke_modeler-0.4.0/lib/cuke_modeler/directory.rb:76:in `block in build_directory'
	from C:/railsinstaller/ruby/gems/2.1.0/gems/cuke_modeler-0.4.0/lib/cuke_modeler/directory.rb:69:in `each'
	from C:/railsinstaller/ruby/gems/2.1.0/gems/cuke_modeler-0.4.0/lib/cuke_modeler/directory.rb:69:in `build_directory'
	from C:/railsinstaller/ruby/gems/2.1.0/gems/cuke_modeler-0.4.0/lib/cuke_modeler/directory.rb:30:in `initialize'
	from C:/railsinstaller/ruby/gems/2.1.0/gems/cql-1.1.0/lib/cql.rb:152:in `new'
	from C:/railsinstaller/ruby/gems/2.1.0/gems/cql-1.1.0/lib/cql.rb:152:in `initialize'
	from C:/project/query_repo/query_repo.rb:3:in `new'
	from C:/project/query_repo/query_repo.rb:3:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'

```

**Comment by enkessler** [comment]
I'm guessing a Windows machine? And is that actually a terminal error or just noise but it keeps working?

**Comment by justjoehere** [comment]
Windows, yes.  Actual terminal error.

**Comment by enkessler** [comment]
Your problem is that you are trying to use a version of the 'gherkin' gem that is not compatible with you Ruby version and OS. If you want to use the 'gherkin' gem, on which 'cql' is eventually based, on Windows with Ruby 2.x, then you'll have to use at least version 3.x of the 'gherkin' gem.

**Comment by justjoehere** [comment]
That fixed it!
